// packages/sdk-vue/src/Test.vue
<script setup lang="ts">
import WalletWidget from '../lib/WalletWidget.vue';
import { useAccount } from '../lib/main';

const { info } = useAccount();
</script>

<template>
  <div>
    <WalletWidget
      clientId="YOUR INTEGRATION UUID HERE"
      :defaultNetworkId="1287"
      :networks="[
        {
          name: 'Moonbeam Testnet',
          id: 1287,
          rpcUrl: 'https://rpc.testnet.moonbeam.network',
          explorerUrl: 'https://moonbase.moonscan.io',
        },
        {
          name: 'Celo Alfajores Testnet',
          id: 44787,
          rpcUrl: 'https://alfajores-forno.celo-testnet.org',
          explorerUrl: 'https://explorer.celo.org/alfajores',
        },
        {
          name: 'Amoy',
          id: 80002,
          rpcUrl: 'https://rpc-amoy.polygon.technology',
          explorerUrl: 'https://www.oklink.com/amoy',
        },
      ]"
    />

    <p>username: {{ info.username }}</p>

    <p>address: {{ info.address }}</p>
  </div>
</template>

// packages/sdk-react/src/Test.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { WalletWidget } from '../lib/WalletWidget';
import { useAccount } from '../lib/main';

export function Test() {
  const { info } = useAccount();

  return (
    <>
      <div>
        <WalletWidget
          clientId="YOUR INTEGRATION UUID HERE"
          defaultNetworkId={1287}
          networks={[
            {
              name: 'Moonbase Testnet',
              id: 1287,
              rpcUrl: 'https://rpc.testnet.moonbeam.network',
              explorerUrl: 'https://moonbase.moonscan.io',
            },
            {
              name: 'Celo Alfajores Testnet',
              id: 44787,
              rpcUrl: 'https://alfajores-forno.celo-testnet.org',
              explorerUrl: 'https://explorer.celo.org/alfajores',
            },
            {
              name: 'Amoy',
              id: 80002,
              rpcUrl: 'https://rpc-amoy.polygon.technology',
              explorerUrl: 'https://www.oklink.com/amoy',
            },
          ]}
        />

        <p>username: {info.username}</p>

        <p>address: {JSON.stringify(info.activeWallet)}</p>
      </div>
    </>
  );
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <Test />
  </React.StrictMode>
);
