// packages/sdk-vue/lib/WalletWidget.vue
<script lang="ts" setup>
import { initializeApp, AppProps } from '@oasis-app-wallet/sdk/ui';
import { onMounted } from 'vue';
import '@oasis-app-wallet/sdk/css';

const props = defineProps<AppProps>();

onMounted(() => {
  initializeApp('#oasis-app-wallet-activator-vue', props);
});
</script>

<template>
  <div id="oasis-app-wallet-activator-vue"></div>
</template>

// packages/sdk-react/lib/components/WalletWidget.tsx
import { AppProps, initializeApp } from '@oasis-app-wallet/sdk/ui';

export function WalletWidget({ className, ...params }: AppProps & { className?: string }) {
  setTimeout(() => {
    initializeApp('#oasis-app-wallet-activator-react', params);
  }, 5);

  return <div id="oasis-app-wallet-activator-react" className={className}></div>;
}
