// apps/next-test/src/components/Test.tsx
'use client';

import { useAccount, WalletWidget } from '@apillon/wallet-react';
import TestSdk from './TestSdk';
import TestViem from './TestViem';
import TestEthers6 from './TestEthers6';
import TestEthers5 from './TestEthers5';

export default function Test() {
  const { info } = useAccount();

  return (
    <div>
      <WalletWidget
        clientId={process.env.NEXT_PUBLIC_CLIENT_ID ?? 'YOUR INTEGRATION UUID HERE'}
        defaultNetworkId={1287}
        networks={[
          {
            name: 'Moonbase Testnet',
            id: 1287,
            rpcUrl: 'https://rpc.testnet.moonbeam.network',
            explorerUrl: 'https://moonbase.moonscan.io',
          },
          {
            name: 'Celo Alfajores Testnet',
            id: 44787,
            rpcUrl: 'https://alfajores-forno.celo-testnet.org',
            explorerUrl: 'https://explorer.celo.org/alfajores',
          },
          {
            name: 'Amoy',
            id: 80002,
            rpcUrl: 'https://rpc-amoy.polygon.technology',
            explorerUrl: 'https://www.oklink.com/amoy',
          },
        ]}
      />

      <div
        style={{
          margin: '16px 0',
          border: 'solid 1px grey',
        }}
      />

      <p>username: {info.username}</p>

      <p>address: {info.address}</p>

      <br />

      <TestSdk />

      <br />

      {!!info.address && <TestViem />}

      <br />

      {!!info.address && <TestEthers6 />}

      <br />

      {!!info.address && <TestEthers5 />}
    </div>
  );
}

// apps/vue-test/src/Test.vue
<script lang="ts" setup>
import { useAccount, WalletWidget } from '@apillon/wallet-vue';
import TestSdk from './TestSdk.vue';
import TestViem from './TestViem.vue';
import TestEthers6 from './TestEthers6.vue';
import TestEthers5 from './TestEthers5.vue';

const { info } = useAccount();

const clientId = import.meta.env.VITE_CLIENT_ID ?? 'YOUR INTEGRATION UUID HERE';
</script>

<template>
  <div>
    <WalletWidget
      :clientId="clientId"
      :defaultNetworkId="1287"
      :networks="[
        {
          name: 'Moonbase Testnet',
          id: 1287,
          rpcUrl: 'https://rpc.testnet.moonbeam.network',
          explorerUrl: 'https://moonbase.moonscan.io',
        },
        {
          name: 'Celo Alfajores Testnet',
          id: 44787,
          rpcUrl: 'https://alfajores-forno.celo-testnet.org',
          explorerUrl: 'https://explorer.celo.org/alfajores',
        },
        {
          name: 'Amoy',
          id: 80002,
          rpcUrl: 'https://rpc-amoy.polygon.technology',
          explorerUrl: 'https://www.oklink.com/amoy',
        },
      ]"
    />

    <div
      :style="{
        margin: '16px 0',
        border: 'solid 1px grey',
      }"
    />

    <p>username: {{ info.username }}</p>

    <p>address: {{ info.address }}</p>

    <br />

    <TestSdk />

    <template v-if="info.address">
      <br />

      <TestViem />

      <br />

      <TestEthers6 />

      <br />

      <TestEthers5 />
    </template>
  </div>
</template>
