// packages/sdk-vue/lib/EmbeddedWallet.vue
<script lang="ts" setup>
import { EmbeddedWalletUI, AppProps } from '@apillon/wallet-ui';
import { onMounted } from 'vue';

const props = defineProps<AppProps>();

onMounted(() => {
  EmbeddedWalletUI('#embedded-wallet-activator-vue', props);
});
</script>

<template>
  <div id="embedded-wallet-activator-vue"></div>
</template>

// packages/sdk-react/lib/EmbeddedWallet.tsx
import { useEffect, useRef } from 'react';
import { EmbeddedWalletUI, AppProps } from '@apillon/wallet-ui';

export function EmbeddedWallet({ className, ...params }: AppProps & { className?: string }) {
  const initialized = useRef(false);

  useEffect(() => {
    setTimeout(() => {
      if (initialized.current) {
        return;
      }

      initialized.current = true;

      EmbeddedWalletUI('#embedded-wallet-activator-react', params);
    }, 5);
  }, []);

  return <div id="embedded-wallet-activator-react" className={className}></div>;
}
